version: '3'

services:
  todotests:
    image: todotests:latest
    restart: always
    depends_on:
      - "todofront"
      - "todoback"
    environment:
      - FRONT_HOST=todofront
  todofront:
    image: todofrontend:latest
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - "todoback"
    environment:
      - REACT_APP_API_HOST=todoback
  todoback:
    image: todobackend:latest
    restart: always
    ports:
      - 3001:3001